Console.WriteLine("Poema Concreto");
Console.WriteLine();
Console.WriteLine();
Console.WriteLine("A");
Console.WriteLine("M");
Console.WriteLine("O");
Console.WriteLine("R");
Console.WriteLine();
Console.WriteLine("A M O R");
Console.WriteLine();
Console.WriteLine("A  M  O  R");
Console.WriteLine();
Console.WriteLine("A   M   O   R");
Console.WriteLine();
Console.WriteLine("A    M    O    R");
Console.WriteLine();
Console.WriteLine("A     M     O     R");
Console.WriteLine();
Console.WriteLine("A      M      O      R");
Console.WriteLine();
Console.WriteLine("A       M       O       R");
Console.WriteLine();
Console.WriteLine("A        M        O        R");
Console.WriteLine();
